import {
  Boxes,
  Briefcase,
  Building,
  CalendarCheck,
  Cloud,
  Cpu,
  Headset,
  GraduationCap,
  HeartPulse,
  Hotel,
  Keyboard,
  Laptop,
  Layers,
  ListChecks,
  Lock,
  Monitor,
  Network,
  PcCase,
  Presentation,
  Printer,
  RefreshCw,
  Server,
  Settings2,
  ShieldCheck,
  ShoppingBag,
  TabletSmartphone,
  Tv,
  Wrench,
  type LucideIcon, MapPinned, Cctv } from 'lucide-react'
import type { ServiceIcon } from '../../data/services'
import type { CategorySlug } from '../../data/types'

export const categoryIcon: Record<CategorySlug, LucideIcon> = {
  'headsets-audio-solutions': Headset,
  'new-laptops': Laptop,
  'refurbished-laptops': RefreshCw,
  'desktops-workstations': PcCase,
  'apple-products': TabletSmartphone,
  'monitors-displays': Monitor,
  'printers-scanners': Printer,
  'it-accessories': Keyboard,
  'components-parts': Cpu,
  networking: Network,
  'servers-storage': Server,
}

export const serviceIcon: Record<ServiceIcon, LucideIcon> = {
  laptop: Laptop,
  wrench: Wrench,
  network: Network,
  calendar: CalendarCheck,
  shield: ShieldCheck,
  lock: Lock,
  cloud: Cloud,
  settings: Settings2,
  presentation: Presentation,
  tv: Tv,
  cctv: Cctv,
}

export const miscIcon: Record<string, LucideIcon> = {
  building: Building,
  heart: HeartPulse,
  cap: GraduationCap,
  bag: ShoppingBag,
  hotel: Hotel,
  briefcase: Briefcase,
  presentation: Presentation,
  layers: Layers,
  boxes: Boxes,
  list: ListChecks,
  settings: Settings2,
  wrench: Wrench,
  map: MapPinned,
  shield: ShieldCheck,
}
