/**
 * IMAGE REGISTRY
 * ---------------------------------------------------------------------------
 * All site imagery is referenced by key from here, so photos can be swapped
 * without touching components.
 *
 * The files in /public/images/products are ORIGINAL, unbranded 3D studio
 * renders generated by `scripts/renders` (Blender). They are representative
 * of each product type and carry no third-party licensing restrictions.
 *
 * To use real photography: drop a file into /public/images/… and change the
 * `src` below (keep 4:3 ratio, transparent or light background, ≥1000px wide).
 * Product-specific photos go on the product itself (product.images) and always
 * take priority over these representative images.
 */
import type { CategorySlug, DeviceArtKind, Product } from './types'

export interface Media {
  src: string
  alt: string
  width: number
  height: number
  /** Fallback illustration if the file fails to load. */
  art: DeviceArtKind
}

/** Base path for image files ('/' in production; './' for the single-file preview build). */
export const IMG_BASE = import.meta.env.VITE_IMAGE_BASE || '/'

const r = (file: string, alt: string, art: DeviceArtKind, w = 1000, h = 750): Media => ({
  src: `${IMG_BASE}images/products/${file}.webp`,
  alt,
  width: w,
  height: h,
  art,
})

/** Transparent cut-outs of PeopleLink product photos from the supplied presentation (dark products only). */
const av = (file: string, alt: string, w: number, h: number): Media => ({
  src: `${IMG_BASE}images/audio-video/cutouts/${file}.webp`,
  alt,
  width: w,
  height: h,
  art: 'monitor',
})

export const media = {
  laptopSilver: r('laptop-silver', 'Silver business laptop, open, 3/4 view', 'laptop'),
  laptopBlack: r('laptop-black', 'Black business laptop, open, 3/4 view', 'laptop'),
  laptopGrey: r('laptop-grey', 'Space-grey premium laptop, open, 3/4 view', 'laptop'),
  laptopPerformance: r('laptop-performance', 'Performance laptop with backlit edge, open', 'laptop'),
  laptopHero: r('laptop-hero', 'Premium laptop showing a business dashboard', 'laptop', 1500, 1125),
  laptopPorts: r('laptop-ports', 'Close-up of laptop keyboard and side ports', 'laptop'),
  desktopTower: r('desktop-tower', 'Desktop tower computer with tempered glass side panel', 'desktop'),
  monitor: r('monitor', 'Widescreen monitor on an aluminium stand', 'monitor'),
  allInOne: r('all-in-one', 'All-in-one desktop computer with slim display', 'monitor'),
  miniPc: r('mini-pc', 'Compact mini PC', 'desktop'),
  server: r('server', 'Stack of rack-mount servers with status lights', 'server'),
  keyboardMouse: r('keyboard-mouse', 'Wireless keyboard and mouse combo', 'keyboard'),
  mouse: r('mouse', 'Wireless mouse', 'keyboard'),
  headset: r('headset', 'Over-ear headset with boom microphone', 'keyboard'),
  webcam: r('webcam', 'HD webcam on a desk stand', 'keyboard'),
  ssdRam: r('ssd-ram', '2.5-inch SSD, M.2 NVMe drive and RAM module', 'component'),
  dock: r('dock', 'USB-C docking station with cable', 'component'),
  charger: r('charger', 'Laptop power adapter with USB-C cable', 'component'),
  laptopStand: r('laptop-stand', 'Adjustable aluminium laptop stand', 'laptop'),
  printer: r('printer', 'Multifunction office printer', 'printer'),
  router: r('router', 'Wi-Fi router with four antennas', 'router'),
  switch: r('switch', '24-port rack-mount network switch', 'router'),
  accessPoint: r('access-point', 'Ceiling-mount Wi-Fi access point', 'router'),
  externalDrive: r('external-drive', 'Portable external hard drive with USB cable', 'component'),
  tablet: r('tablet', 'Tablet on a desk stand', 'tablet'),
  signage: r('signage', 'Portrait digital signage display', 'monitor'),
  conference: r('conference', 'Video conferencing display with camera bar', 'monitor'),
  firewall: r('firewall', 'Network firewall appliance', 'server'),
  batteryParts: r('battery-parts', 'Laptop battery, circuit board and cooling fan', 'component'),
  cables: r('cables', 'Coiled computer cables', 'component'),
  projector: r('projector', 'Business projector', 'monitor'),
  speakers: r('speakers', 'Pair of studio speakers', 'monitor'),
  videoWall: r('video-wall', '3×2 LED video wall on stands', 'monitor'),
  kiosk: r('kiosk', 'Free-standing touch kiosk with portrait screen', 'monitor'),
  menuBoard: r('menu-board', 'Three-screen digital menu board', 'monitor'),
  avSoundbar: av('soundbar', 'PeopleLink 4K AF camera soundbar', 1000, 235),
  avQuadro: av('quadro', 'PeopleLink Quadro conference speakerphone', 766, 508),
  avUvc15: av('uvc-15', 'PeopleLink UVC 15 USB speakerphone', 919, 645),
  avWebcam: av('i8-webcam', 'PeopleLink i8 Plus webcam', 998, 588),
  avCeilingMic: av('dsp-cm-pro', 'PeopleLink DSP-CM Pro with ceiling microphones', 994, 529),
  avPtz: av('icam-12x', 'PeopleLink iCam WHD 1080 USB 12X PTZ camera kit', 869, 703),
  smartphones: r('smartphones', 'Two smartphones, screen and camera side (representative render)', 'tablet'),
  earbuds: r('earbuds', 'Wireless earbuds with charging case (representative render)', 'keyboard'),
  smartwatch: r('smartwatch', 'Smartwatch with sport band (representative render)', 'tablet'),
  wirelessCharger: r('wireless-charger', 'Magnetic wireless charger with USB-C power adapter (representative render)', 'component'),
  headsetStereo: r('headset-stereo', 'Wired stereo USB headset with boom microphone (representative render)', 'keyboard'),
  headsetMono: r('headset-mono', 'Mono contact-centre headset with boom microphone (representative render)', 'keyboard'),
  headsetWireless: r('headset-wireless', 'Wireless office headset on a charging stand with USB adapter (representative render)', 'keyboard'),
  speakerphone: r('speakerphone', 'Conference speakerphone with light ring (representative render)', 'keyboard'),
  headsetAccessories: r('headset-accessories', 'Replacement ear cushions, USB-C adapter and cable (representative render)', 'component'),
  headsetWorkstation: r('headset-workstation', 'Laptop with headset on a stand and a speakerphone (representative render)', 'laptop'),
  cctv: r('cctv', 'Dome and bullet CCTV cameras (representative render)', 'router'),
  mediaPlayer: r('media-player', 'Compact digital signage media player', 'desktop'),
} satisfies Record<string, Media>

export type MediaKey = keyof typeof media

export const categoryMedia: Record<CategorySlug, MediaKey> = {
  'new-laptops': 'laptopSilver',
  'refurbished-laptops': 'laptopBlack',
  'desktops-workstations': 'desktopTower',
  'apple-products': 'smartphones',
  'monitors-displays': 'monitor',
  'printers-scanners': 'printer',
  'it-accessories': 'keyboardMouse',
  'components-parts': 'ssdRam',
  networking: 'router',
  'servers-storage': 'server',
  'headsets-audio-solutions': 'headsetStereo',
}

/** Chooses a representative image for a product without its own photos. */
export function productMediaKey(p: Product): MediaKey {
  if (p.imageKey) return p.imageKey
  const t = `${p.name} ${p.subcategory ?? ''}`.toLowerCase()
  if (p.category === 'new-laptops' || p.category === 'refurbished-laptops') {
    if (/legion|performance|gaming/.test(t)) return 'laptopPerformance'
    if (/macbook|xps|premium|elitebook 840 g11/.test(t)) return 'laptopGrey'
    if (/thinkpad|latitude 7|used/.test(t)) return 'laptopBlack'
    return 'laptopSilver'
  }
  if (p.category === 'desktops-workstations') {
    if (/mini/.test(t)) return 'miniPc'
    if (/all-in-one|aio/.test(t)) return 'allInOne'
    return 'desktopTower'
  }
  if (p.category === 'apple-products') {
    if (/macbook/.test(t)) return 'laptopGrey'
    if (/imac/.test(t)) return 'allInOne'
    if (/mac mini/.test(t)) return 'miniPc'
    if (/iphone/.test(t)) return 'smartphones'
    if (/airpods/.test(t)) return 'earbuds'
    if (/watch/.test(t)) return 'smartwatch'
    if (/magsafe|wireless charger/.test(t)) return 'wirelessCharger'
    if (/adapter|charger/.test(t)) return 'charger'
    if (/keyboard|mouse|trackpad/.test(t)) return 'keyboardMouse'
    if (/cable/.test(t)) return 'cables'
    return 'tablet'
  }
  if (p.category === 'it-accessories') {
    if (/keyboard|mouse/.test(t)) return 'keyboardMouse'
    if (/charger|adapter/.test(t)) return 'charger'
    if (/dock|hub/.test(t)) return 'dock'
    if (/headset|webcam/.test(t)) return /webcam/.test(t) ? 'webcam' : 'headset'
    if (/stand/.test(t)) return 'laptopStand'
    if (/cable/.test(t)) return 'cables'
    return 'keyboardMouse'
  }
  if (p.category === 'components-parts') {
    if (/external/.test(t)) return 'externalDrive'
    if (/battery|replacement/.test(t)) return 'batteryParts'
    return 'ssdRam'
  }
  if (p.category === 'networking') {
    if (/switch/.test(t)) return 'switch'
    if (/access point/.test(t)) return 'accessPoint'
    if (/firewall/.test(t)) return 'firewall'
    return 'router'
  }
  if (p.category === 'headsets-audio-solutions') {
    if (/speakerphone|sync|speak2|meeting/.test(t)) return 'speakerphone'
    if (/accessor|cushion|adapter|cable/.test(t)) return 'headsetAccessories'
    if (/wireless|bluetooth|voyager|evolve2 65|zone vibe|730/.test(t)) return 'headsetWireless'
    if (/call centre|encorepro|engage|mono/.test(t)) return 'headsetMono'
    return 'headsetStereo'
  }
  if (p.category === 'monitors-displays') return /signage|interactive/.test(t) ? 'signage' : 'monitor'
  if (p.category === 'servers-storage') return /nas|storage/.test(t) ? 'externalDrive' : 'server'
  return categoryMedia[p.category]
}
